Add install and uninstall script, complete README file.

diff --git a/vms b/vms
--- a/vms
+++ b/vms
@@ -8,13 +8,120 @@ fi
 
 . "${VMS_HOME}"/conf/vms.properties
 . "${VMS_HOME}"/conf/module.properties
-. "${VMS_HOME}"/plugin/vms.sh
 . "${VMS_HOME}"/conf/plugins
-echo -e "Vertical Management Suite \033[35m${Version}\033[0m, Powered by \033[34m${Author}\033[0m"
+his_file="${VMS_HOME}"/log/vms.history
+
+# disable exit
+exit(){
+    echo -e "\e[31mexit is disabled, please use return statement.\e[0m"
+}
+
+help() {
+    if [ "$#" -eq 0 ]; then
+        cat "${VMS_HOME}"/man/vms.man
+    else
+        cat "${VMS_HOME}"/man/"${1}".man
+    fi
+}
+
+version(){
+    echo -e "Vertical Management Suite \e[35m${Version}\e[0m, Powered by \e[33m${Author}\e[0m"
+}
+
+info() {
+    version
+    echo -e "// TODO shows infos of vms, modules, system, etc."
+}
+
+vcd(){
+    cd "$@"
+}
+
+history(){
+
+    if [ "$#" -eq 0 ]; then
+        cat -n "${his_file}"
+        echo -e "\e[33mNote: Navigation key viewing history is currently not supported.\e[0m"
+        return 0
+    fi
+
+    his_paras=$(getopt -o +cw -n "${FUNCNAME[0]}" -- "$@")
+    [ "$?" != 0 ] && return 1
+    eval set -- "${his_paras}"
+    while true ; do
+        case "${1}" in
+            -c)
+                shift
+                echo -n "" > "${his_file}"
+                return 0
+                ;;
+            -w)
+                shift
+                history_rows=$(wc -l < "${his_file}")
+                of_rows=$[history_rows-HistoryMax]
+                [ "${of_rows}" -gt 0 ] && sed -i "1,${of_rows}d" "${his_file}"
+                return 0
+                ;;
+            --)
+                shift
+                ;;
+            *)
+                [[ "${1}" = *[!0-9]* ]] && echo -e "\e[31m${1} is not a NUMBER!\e[0m" && return 2
+                echo $(sed -n "${1},${1}p" "${his_file}")
+                vms_main $(sed -n "${1},${1}p" "${his_file}")
+                return 0
+                ;;
+        esac
+    done
+}
+
+his(){
+    history "$@"
+}
+
+:(){
+    cat -n "${his_file}" | grep "$*"
+}
+
+!!(){
+    history $[$(wc -l < "${his_file}")-1]
+}
+
+vms_main(){
+    echo "$@" >> "${his_file}"
+    cmd="$@"
+    if [ "#" == "${cmd:0:1}" ]; then
+        cmd="${cmd:1}"
+        ${cmd}
+    elif [ ":" == "${cmd:0:1}" ]; then
+        cmd="${cmd:1}"
+        : "${cmd}"
+    else
+        do_vms "${cmd}"
+    fi
+}
+
+do_vms() {
+    eval set -- "${cmd}"
+    vms_cmd="${1}"
+    [[ "${vms_cmd}" = "do_vms" ]] && echo -e "\e[31mBad Command!\e[0m" && return -1
+    [[ "${vms_cmd}" = "exit" ]] && history -w && unset -f exit && exit
+    [[ "${vms_cmd}" = "cd" ]] && vms_cmd="vcd"
+    if [ "$(type -t "${vms_cmd}")" = "function" ]; then
+        shift
+        ${vms_cmd} "$@"
+    else
+        echo -e "\e[31m${1}: Command Not Found!\e[0m"
+    fi
+}
+
+# Main body
+version
 echo
+
 while true; do
     wd=$(pwd)
-    read -ep $'\033[35m'"[vms-cli ${wd}]# "$'\033[0m' cmd
+    read -ep $'\e[35m'"[vms-cli ${wd}]# "$'\e[0m' cmd
     vms_main "${cmd}"
     echo
 done
