new version: v0.5_20230101; Add: multi-host sync file, update variables, start modules; Fix: install and uninstall scripts uses wrong file name.

diff --git a/vms b/vms
--- a/vms
+++ b/vms
@@ -40,38 +40,72 @@ info() {
     echo -e "// TODO shows infos of vms, modules, system, etc."
 }
 
-mrun() {
-    [ $# -lt 1 ] && echo -e "Parameter missing!" && return 1
-    mrun_paras=$(getopt -o +h: -n "${FUNCNAME[0]}" -- "$@")
-    [ $? -ne 0 ] && return 1
-    eval set -- "${mrun_paras}"
-    while true; do
-        case "${1}" in
-        -h)
-            Nodes="${2}"
-            shift 2
-            ;;
-        --)
-            shift
-            ;;
-        *)
-            break
-            ;;
-        esac
-    done
+status() {
+    echo "// TODO"
+    [[ "${1}" == "-s" ]] && local silent_flag="yes" && shift
+    # -s silent==> ignore echo
+    local s_code
+    local res
+    res=$(status_"${1}")
+    s_code=$?
+    [ "${silent_flag}" ] || echo "${res}"
+    echo "${s_code}"
+    return "${s_code}"
+}
 
-    o_ifs="${IFS}"
-    IFS=','
-    hosts=(${Nodes})
-    IFS="${o_ifs}"
-
-    for host in "${hosts[@]}"; do
-        echo "======= running command [$@] on ${host}... ======="
-        # ssh "${User}"@"${host}" "$@"
+start() {
+    verify_module "$@" || return 1
+    local start_module
+    for start_module in "${StartOrder[@]}"; do
+        is_in "${start_module}" "$@" || continue
+        is_in "${start_module}" "${!Dependencies[@]}" && start ${Dependencies[${start_module}]}
+        echo "============== starting ${start_module}... =============="
+        status -s "${start_module}" && echo start_"${start_module}" || echo "${start_module} is already running."
     done
 }
 
-m(){
+sync() {
+    [ $# -lt 1 ] && echo -e "Parameter missing!" && return 1
+    get_hosts
+    for host in "${hosts[@]}"; do
+        echo "======= syncing files to ${host}... ======="
+        for file in "$@"; do
+            if [ -e "${file}" ]; then
+                pdir=$(
+                    cd -P $(dirname ${file})
+                    pwd
+                )
+                fname=$(basename "${file}")
+                ssh "${User}"@"${host}" "mkdir -p ${pdir}"
+                rsync -av "${pdir}"/"${fname}" "${User}"@"${host}":"${pdir}"
+            else
+                echo "-vms: ${file}: No such file or directory!"
+            fi
+        done
+    done
+}
+
+update() {
+    for seg in "$@"; do
+        local var="${seg%%=*}"
+        [ "${!var}" ] && eval "${seg}" || echo "${var} is not assigned"
+    done
+}
+
+up() {
+    update "$@"
+}
+
+mrun() {
+    [ $# -lt 1 ] && echo -e "Parameter missing!" && return 1
+    get_hosts
+    for host in "${hosts[@]}"; do
+        echo "======= running command on ${host}... ======="
+        ssh "${User}"@"${host}" "$@"
+    done
+}
+
+m() {
     mrun "$@"
 }
 
@@ -142,8 +176,6 @@ do_vms() {
 # Main body
 version
 echo
-
-alias m='mrun'
 
 while true; do
     wd=$(pwd)
